name: Docs

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - name: MkDocs strict build
        run: python3 -m mkdocs build --strict
